### ISSUE TITLE
Decide what Apollo (and other gateware) will do on older Cynthion revisions

### ISSUE THREAD

**Issue by straithe** [greatscottgadgets/apollo#26]
July 2023, issue #21 states that "From everything I can tell, at the moment there is no way to actually use the sideband PHY port from the FPGA. At least on the Luna v0.4 that I have." @martinling mentions that Apollo works quite differently in later versions of the Cynthion hardware, compared to v0.4 of Cynthion. Martin goes on to explain more about the changes and answers each of the questions in the issue, but a new issue remains to be resolved: What Apollo and other gateware should do on older board revisions.

**Comment by mossmann** [comment]
reopened #21 instead
