### ISSUE TITLE
Update LED usage

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/apollo#39]
Proposed plan:
- ~~LED A: USB switch is in Apollo/Saturn-V mode (see #38)~~
- ~~LED B: FPGA is being held offline~~
- ~~LED C: Saturn-V heartbeat~~
- ~~LED D: fault, e.g. FPGA failed to configure from flash~~
- ~~LED E: Apollo heartbeat~~

[proposal replaced by "Alternative scheme" in comment below]

All LEDs would change function temporarily if a pattern other than idle is in use. The idle pattern would restore the indications above.

**Comment by martinling** [comment]
Personally I would love it if the LEDs would stop flashing when nothing is happening (e.g. Apollo is idle and a bitstream is running OK). To me, flashing means something is wrong and it wants attention.
